services:
  database-service:
    image: mongo:8.0
    container_name: database-service-container
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: events-management-solution
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
      - ./DatabaseService/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app_network

  mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database-service
      ME_CONFIG_MONGODB_ADMINUSERNAME: user123
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
    depends_on:
      - database-service
    networks:
      - app_network

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
