services:
  database-service:
    image: mongo:8.0
    container_name: database-service-container
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: events-management-solution
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db
      - ./.docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app_network

  mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database-service
      ME_CONFIG_MONGODB_ADMINUSERNAME: user123
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
    depends_on:
      - database-service
    networks:
      - app_network

  localstack:
    container_name: localstack-container
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
      - DEBUG=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  ses-verifier:
    image: amazon/aws-cli:latest
    container_name: ses-verifier-container
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: ["/bin/sh", "-c"]
    command:
      - aws --endpoint-url=http://localstack:4566 ses verify-email-identity --email-address noreply@ems.local --region us-east-1
    networks:
      - app_network
    restart: "no"

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
